### ISSUE TITLE
Incompatible with GeneralImprovements' monitors

### ISSUE THREAD

**Issue by throwitaway99** [julian-perge/LC_OpenMonitors#3]
If using OpenMonitors in conjunction with [GeneralImprovements](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements) (specifically whilst any monitors are modified from the default in GeneralImprovements), then the Players Life Support overlay no longer functions, with any enabled OpenMonitors monitors appearing black. I've personally found that the Players Life Support overlay is my favorite feature, and compatibility would be much appreciated. I can report that it luckily works just fine with OpenBodyCams, so GeneralImprovements is the only mod I've found incompatible thus far.

**Comment by julian-perge** [comment]
Thanks for the report!

I had no idea this mod added extra monitors. I'll reach out to the mod creator and see if they'll be interested in merging these together into their own repo, since the general outcome of each is roughly the same.
