### ISSUE TITLE
[Bug] Many config entries don't generate and HideWeather doesn't work

### ISSUE THREAD

**Issue by zndrmn** [julian-perge/LC_OpenMonitors#8]
The list of configs that don't work or generate:
Here's my config file [xxxstoner420bongmasterxxx-open_monitors.cfg](https://gist.github.com/zndrmn/ceccc02a1b7ddc3066b7653282f01d51#file-xxxstoner420bongmasterxxx-open_monitors-cfg)

HideWeather (doesn't seem to do anything, and the rest don't show up in the config file)

KeepBlueBackground1
KeepBlueBackground2

NoneWeatherColor 
RainyWeatherColor
FoggyWeatherColor
StormyWeatherColor
FloodedWeatherColor
EclipsedWeatherColor
DustCloudsWeatherColor

**Comment by julian-perge** [comment]
Sorry about that! Been very busy at work, just got around to pushing the update to thunderstore.

Both these issues should be fixed in the latest v1.1.0 release. Please confirm on your side, thanks!

**Comment by zndrmn** [comment]
Everything works perfectly now!
